export type HttpMethod = 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE';

export interface ApiErrorBody {
  code?: string;
  message?: string;
  target?: string;
  details?: unknown;
}

export class ApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly body: ApiErrorBody | null;

  constructor(status: number, message: string, body: ApiErrorBody | null = null) {
    super(message);
    this.name = 'ApiError';
    this.status = status;
    this.code = body?.code ?? `http_${status}`;
    this.body = body;
  }

  get isUnauthorized(): boolean {
    return this.status === 401 || this.status === 403;
  }
}

export type TokenProvider = () => Promise<string | null>;

export interface RequestOptions {
  method?: HttpMethod;
  body?: BodyInit | null;
  /** Set for multipart uploads; the boundary is generated by the browser. */
  rawBody?: boolean;
  accept?: string;
  headers?: Record<string, string>;
  token?: string | null;
  signal?: AbortSignal;
  /** Skip the Authorization header (used for the dev token endpoint). */
  anonymous?: boolean;
}

export async function readErrorBody(response: Response): Promise<ApiErrorBody | null> {
  const contentType = response.headers.get('content-type') ?? '';
  if (contentType.includes('application/json')) {
    try {
      return (await response.json()) as ApiErrorBody;
    } catch {
      return null;
    }
  }
  return null;
}

export async function request(url: string, options: RequestOptions = {}): Promise<Response> {
  const headers: Record<string, string> = {
    Accept: options.accept ?? 'application/json',
    ...options.headers,
  };

  if (options.token && !options.anonymous) {
    headers.Authorization = `Bearer ${options.token}`;
  }
  if (options.body !== undefined && options.body !== null && !options.rawBody) {
    headers['Content-Type'] = 'application/json';
  }

  const response = await fetch(url, {
    method: options.method ?? 'GET',
    headers,
    body: options.body ?? null,
    signal: options.signal,
  });

  if (!response.ok) {
    const body = await readErrorBody(response);
    throw new ApiError(response.status, body?.message ?? `Request failed with status ${response.status}`, body);
  }

  return response;
}

export async function requestJson<T>(url: string, options: RequestOptions = {}): Promise<T> {
  const response = await request(url, { ...options, accept: options.accept ?? 'application/json' });
  if (response.status === 204) {
    return undefined as T;
  }
  return (await response.json()) as T;
}
