package com.acme.usermark.dev;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import org.springframework.web.multipart.MultipartFile;

/**
 * Presents generated bytes as an upload so that the demo documents travel the
 * same path as a browser upload, including name sanitising, size limit and
 * checksum. MultipartFile is a plain interface, no test library is needed.
 */
class ByteArrayUpload implements MultipartFile {

    private final String name;
    private final String contentType;
    private final byte[] content;

    ByteArrayUpload(String name, String contentType, byte[] content) {
        this.name = name;
        this.contentType = contentType;
        this.content = content.clone();
    }

    @Override
    public String getName() {
        return "file";
    }

    @Override
    public String getOriginalFilename() {
        return name;
    }

    @Override
    public String getContentType() {
        return contentType;
    }

    @Override
    public boolean isEmpty() {
        return content.length == 0;
    }

    @Override
    public long getSize() {
        return content.length;
    }

    @Override
    public byte[] getBytes() {
        return content.clone();
    }

    @Override
    public InputStream getInputStream() {
        return new ByteArrayInputStream(content);
    }

    @Override
    public void transferTo(File destination) throws IOException, IllegalStateException {
        Files.write(destination.toPath(), content);
    }

    @Override
    public void transferTo(Path destination) throws IOException, IllegalStateException {
        Files.write(destination, content);
    }

    @Override
    public String toString() {
        return "ByteArrayUpload[" + contentType + ", " + content.length + " bytes]";
    }
}